-- Link owner dashboard: product usage analytics and immutable admin audit log.
-- Safe to run more than once in the Supabase SQL editor.

create table if not exists public.app_usage_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  church_id uuid references public.churches(id) on delete set null,
  event_name text not null check (event_name in ('app_open', 'sign_in')),
  platform text not null,
  app_version text,
  build_number text,
  occurred_at timestamptz not null default now()
);

create index if not exists idx_app_usage_events_occurred_at
  on public.app_usage_events (occurred_at desc);
create index if not exists idx_app_usage_events_user_activity
  on public.app_usage_events (user_id, occurred_at desc);
create index if not exists idx_app_usage_events_church_activity
  on public.app_usage_events (church_id, occurred_at desc);

alter table public.app_usage_events enable row level security;
revoke all on public.app_usage_events from anon;
grant insert on public.app_usage_events to authenticated;

drop policy if exists "usage_events_insert_own" on public.app_usage_events;
create policy "usage_events_insert_own" on public.app_usage_events
for insert to authenticated
with check (
  user_id = auth.uid()
  and church_id = public.current_church_id()
);

-- No authenticated SELECT policy is intentional. Product analytics is only
-- read from the protected server dashboard using the service-role key.

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  -- Keep the historical actor UUID even if that Auth account is deleted.
  admin_user_id uuid not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  table_name text not null,
  row_id text,
  changes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs
  drop constraint if exists admin_audit_logs_admin_user_id_fkey;

create index if not exists idx_admin_audit_logs_created_at
  on public.admin_audit_logs (created_at desc);
create index if not exists idx_admin_audit_logs_table_row
  on public.admin_audit_logs (table_name, row_id);

alter table public.admin_audit_logs enable row level security;
revoke all on public.admin_audit_logs from anon, authenticated;

comment on table public.app_usage_events is
  'Minimal authenticated product analytics for the Link owner dashboard.';
comment on table public.admin_audit_logs is
  'Immutable record of database changes made through Link Control.';
