import Link from 'next/link';
import { getEnhancedDashboardData } from '@/lib/admin/data';
import { requireSuperAdmin } from '@/lib/admin/auth';

const n = (value: number) => new Intl.NumberFormat('ar-EG').format(value);
const category = (value: string | null) => ({ login: 'تسجيل الدخول', attendance: 'الحضور', members: 'الأعضاء', invitations: 'الدعوات', notifications: 'الإشعارات', other: 'أخرى' } as Record<string, string>)[value ?? ''] ?? '—';
const activityDate = (value: string | null) => value ? new Date(value).toLocaleString('ar-EG', { dateStyle: 'medium', timeStyle: 'short' }) : 'لا يوجد نشاط';

export default async function AdminDashboardPage({ searchParams }: { searchParams: Promise<{ days?: string; church?: string }> }) {
  await requireSuperAdmin();
  const search = await searchParams;
  const days = search.days === '7' || search.days === '90' ? Number(search.days) as 7 | 90 : 30;
  const data = await getEnhancedDashboardData({ days, churchId: search.church || undefined });
  const { summary } = data;
  const link = (period: number) => `/admin?days=${period}${search.church ? `&church=${encodeURIComponent(search.church)}` : ''}`;

  return <main className="adminContent enhancedDashboard">
    <div className="pageTitle"><div><span>لوحة القرار</span><h1>صحة المنظومة والخدمة</h1><p>مؤشرات فعلية حسب الكنيسة والفترة المختارة.</p></div><div className="updatedAt">آخر تحديث {new Date(data.generatedAt).toLocaleString('ar-EG')}</div></div>
    <form className="dashboardFilters" method="get"><div><span>الفترة</span>{([7, 30, 90] as const).map((value) => <Link key={value} className={days === value ? 'selected' : ''} href={link(value)}>{value === 7 ? 'أسبوع' : value === 30 ? 'شهر' : '3 شهور'}</Link>)}</div><label>الكنيسة<select name="church" defaultValue={search.church ?? ''}><option value="">كل الكنائس</option>{data.churches.map((church) => <option key={String(church.id)} value={String(church.id)}>{String(church.name_ar || church.name)}</option>)}</select></label><input type="hidden" name="days" value={days} /><button type="submit">تطبيق</button></form>

    <section className="metricGrid decisionMetrics"><article><span className="metricIcon teal">✓</span><small>تفعيل الكنائس</small><strong>{summary.activeChurchRate}%</strong><em>{n(summary.activeChurches)} كنيسة لديها خدام واجتماعات وحضور</em></article><article><span className="metricIcon purple">♙</span><small>مخدومون جدد</small><strong>{n(summary.currentMembers)}</strong><em>خلال الفترة المختارة</em></article><article><span className="metricIcon blue">✓</span><small>الحضور</small><strong>{n(summary.present)}</strong><em>{n(summary.absent)} غياب مسجل</em></article><article><span className="metricIcon amber">!</span><small>الدعم المفتوح</small><strong>{data.supportReady ? n(summary.openSupport) : '—'}</strong><em>{summary.avgResolutionHours === null ? 'لا توجد حالات محلولة' : `متوسط الحل ${summary.avgResolutionHours} ساعة`}</em></article></section>

    <section className="dashboardGrid"><article className="tableCard wide"><header><div><h2>الكنائس الأكثر والأقل نشاطًا</h2><p>الحضور والجلسات وآخر استخدام أو جلسة مسجلة.</p></div><Link href="/admin/data/churches">إدارة الكنائس</Link></header><div className="simpleTable activityTable"><div className="tableHead"><span>الكنيسة</span><span>الحضور</span><span>الجلسات</span><span>آخر نشاط</span></div>{data.churchActivity.slice(0, 5).map((church) => <div key={church.id}><strong>{church.name}</strong><span>{n(church.attendance)}</span><span>{n(church.sessions)}</span><span>{activityDate(church.lastActivity)}</span></div>)}</div>{!!data.churchActivity.length && <p className="quietChurches">الأقل نشاطًا: {data.churchActivity.slice(-3).reverse().map((church) => church.name).join('، ')}</p>}</article><article className="attentionCard"><header><h2>تحتاج انتباهك</h2><span>{data.repeatedAbsences.length + data.pendingInvitations.length + data.inactiveProfiles.length + summary.unresolvedFollowUps}</span></header><div><b>{data.repeatedAbsences.length}</b><span>مخدومون بغياب متكرر</span><Link href="/admin/data/follow_ups">متابعة ←</Link></div><div><b>{data.pendingInvitations.length}</b><span>دعوات لم تُقبل</span><Link href="/admin/data/invitations">مراجعة ←</Link></div><div><b>{data.inactiveProfiles.length}</b><span>حسابات غير نشطة</span><Link href="/admin/data/profiles">مراجعة ←</Link></div></article></section>

    <section className="dashboardGrid"><article className="tableCard wide"><header><div><h2>أداء الاجتماعات</h2><p>المنضمون الجدد والحضور والغياب والنمو خلال الفترة.</p></div><Link href="/admin/data/meetings">كل الاجتماعات</Link></header><div className="simpleTable performanceTable"><div className="tableHead"><span>الاجتماع</span><span>جدد</span><span>حضور / غياب</span><span>النمو</span></div>{data.meetingPerformance.slice(0, 8).map((meeting) => <div key={meeting.id}><strong>{meeting.name}<small>{meeting.church}</small></strong><span>{n(meeting.newMembers)}</span><span>{n(meeting.present)} / {n(meeting.absent)}</span><span className={meeting.change >= 0 ? 'statusActive' : 'statusQuiet'}>{meeting.change >= 0 ? '+' : ''}{meeting.change}%</span></div>)}</div></article><article className="distributionCard"><h2>الدعوات</h2><p>خلال الفترة المختارة</p><div><span>مرسلة</span><b>{n(summary.invitationStats.sent)}</b></div><div><span>مقبولة</span><b>{n(summary.invitationStats.accepted)}</b></div><div><span>معلّقة</span><b>{n(summary.invitationStats.pending)}</b></div><div><span>مرفوضة</span><b>{n(summary.invitationStats.declined)}</b></div><h3>أكثر مشكلة متكررة</h3><div><span>{data.supportReady ? category(summary.topCategory) : 'غير متاح'}</span><b>{data.supportReady ? 'الدعم' : '—'}</b></div></article></section>

    <section className="servantsCard"><header><div><h2>الخدام والصلاحيات</h2><p>كل خادم وتكليفاته في الاجتماعات أو الفصول. استخدم فلتر الكنيسة في الأعلى للتركيز على كنيسة واحدة.</p></div><Link href="/admin/data/class_assignments">إدارة التكليفات</Link></header>{data.servantPermissions.length ? <div className="servantsList">{data.servantPermissions.map((servant) => <article key={servant.id}><div className="servantHeading"><strong>{servant.name}</strong><span>{servant.church}</span><em>{servant.role}</em></div>{servant.assignments.length ? <ul>{servant.assignments.map((assignment) => <li key={`${servant.id}-${assignment.target}`}><b>{assignment.target}</b><span className={assignment.attendance ? 'permissionYes' : 'permissionNo'}>تسجيل حضور: {assignment.attendance ? 'مسموح' : 'غير مسموح'}</span><span className={assignment.reports ? 'permissionYes' : 'permissionNo'}>تقارير: {assignment.reports ? 'مسموح' : 'غير مسموح'}</span></li>)}</ul> : <p className="noAssignment">لا توجد تكليفات محددة لهذا الخادم.</p>}</article>)}</div> : <div className="emptyMetric">لا توجد حسابات خدام مطابقة للفلتر الحالي.</div>}</section>

    <section className="dashboardGrid"><article className="tableCard wide"><header><div><h2>غياب متكرر</h2><p>مخدومون لديهم غياب مرتين أو أكثر خلال الفترة.</p></div><Link href="/admin/data/attendance_records">السجلات</Link></header><div className="nameChips">{data.repeatedAbsences.length ? data.repeatedAbsences.map((entry) => <span key={entry.name}><b>{entry.name}</b> {entry.count} مرات</span>) : <em>لا توجد حالات غياب متكرر في الفترة المختارة.</em>}</div></article><article className="distributionCard"><h2>الحسابات غير النشطة</h2>{data.inactiveProfiles.length ? data.inactiveProfiles.map((profile) => <div key={`${profile.name}-${profile.church}`}><span>{profile.name}</span><b>{profile.church}</b></div>) : <div className="emptyMetric">لا توجد حسابات غير نشطة.</div>}</article></section>
  </main>;
}
