import Link from 'next/link';
import { getEnhancedDashboardData } from '@/lib/admin/data';
import { requireSuperAdmin } from '@/lib/admin/auth';

const n = (value: number) => new Intl.NumberFormat('ar-EG').format(value);
const category = (value: string | null) => ({ login: 'تسجيل الدخول', attendance: 'الحضور', members: 'الأعضاء', invitations: 'الدعوات', notifications: 'الإشعارات', other: 'أخرى' } as Record<string, string>)[value ?? ''] ?? '—';
const activityDate = (value: string | null) => value ? new Date(value).toLocaleString('ar-EG', { dateStyle: 'medium', timeStyle: 'short' }) : 'لا يوجد نشاط';
const actionLabel = (value: string) => ({ insert: 'إضافة', update: 'تعديل', delete: 'حذف' } as Record<string, string>)[value] ?? value;
function AttendanceBars({ points }: { points: Array<{ date: string; count: number }> }) { const max = Math.max(1, ...points.map((point) => point.count)); return <div className="attendanceBars" aria-label="اتجاه الحضور"><div>{points.map((point) => <i key={point.date} title={`${point.date}: ${point.count}`} style={{ height: `${Math.max(4, point.count / max * 100)}%` }} />)}</div></div>; }

export default async function AdminDashboardPage({ searchParams }: { searchParams: Promise<{ days?: string; church?: string; servantsQ?: string; servantPage?: string }> }) {
  await requireSuperAdmin();
  const search = await searchParams;
  const days = search.days === '7' || search.days === '90' ? Number(search.days) as 7 | 90 : 30;
  const data = await getEnhancedDashboardData({ days, churchId: search.church || undefined });
  const { summary } = data;
  const link = (period: number) => `/admin?days=${period}${search.church ? `&church=${encodeURIComponent(search.church)}` : ''}`;
  const servantsQuery = (search.servantsQ ?? '').trim().toLocaleLowerCase('ar');
  const matchingServants = data.servantPermissions.filter((servant) => !servantsQuery || `${servant.name} ${servant.church} ${servant.role}`.toLocaleLowerCase('ar').includes(servantsQuery));
  const servantPage = Math.max(1, Number(search.servantPage ?? '1'));
  const servantPages = Math.max(1, Math.ceil(matchingServants.length / 10));
  const visibleServants = matchingServants.slice((servantPage - 1) * 10, servantPage * 10);
  const servantsLink = (page: number) => `/admin?days=${days}${search.church ? `&church=${encodeURIComponent(search.church)}` : ''}&servantsQ=${encodeURIComponent(search.servantsQ ?? '')}&servantPage=${page}`;

  return <main className="adminContent enhancedDashboard">
    <div className="pageTitle"><div><span>لوحة القرار</span><h1>صحة المنظومة والخدمة</h1><p>مؤشرات فعلية حسب الكنيسة والفترة المختارة.</p></div><div className="updatedAt">آخر تحديث {new Date(data.generatedAt).toLocaleString('ar-EG')}</div></div>
    <form className="dashboardFilters" method="get"><div><span>الفترة</span>{([7, 30, 90] as const).map((value) => <Link key={value} className={days === value ? 'selected' : ''} href={link(value)}>{value === 7 ? 'أسبوع' : value === 30 ? 'شهر' : '3 شهور'}</Link>)}</div><label>الكنيسة<select name="church" defaultValue={search.church ?? ''}><option value="">كل الكنائس</option>{data.churches.map((church) => <option key={String(church.id)} value={String(church.id)}>{String(church.name_ar || church.name)}</option>)}</select></label><input type="hidden" name="days" value={days} /><button type="submit">تطبيق</button></form>

    <section className="metricGrid decisionMetrics"><article><span className="metricIcon teal">✓</span><small>تفعيل الكنائس</small><strong>{summary.activeChurchRate}%</strong><em>{n(summary.activeChurches)} كنيسة لديها خدام واجتماعات وحضور</em></article><article><span className="metricIcon purple">♙</span><small>مخدومون جدد</small><strong>{n(summary.currentMembers)}</strong><em>خلال الفترة المختارة</em></article><article><span className="metricIcon blue">✓</span><small>الحضور</small><strong>{n(summary.present)}</strong><em>{n(summary.absent)} غياب مسجل</em></article><article><span className="metricIcon amber">!</span><small>الدعم المفتوح</small><strong>{data.supportReady ? n(summary.openSupport) : '—'}</strong><em>{summary.avgResolutionHours === null ? 'لا توجد حالات محلولة' : `متوسط الحل ${summary.avgResolutionHours} ساعة`}</em></article></section>

    <section className="dashboardGrid"><article className="tableCard wide"><header><div><h2>الكنائس الأكثر والأقل نشاطًا</h2><p>الحضور والجلسات وآخر استخدام أو جلسة مسجلة.</p></div><Link href="/admin/data/churches">إدارة الكنائس</Link></header><div className="simpleTable activityTable"><div className="tableHead"><span>الكنيسة</span><span>الحضور</span><span>الجلسات</span><span>آخر نشاط</span></div>{data.churchActivity.slice(0, 5).map((church) => <div key={church.id}><strong>{church.name}</strong><span>{n(church.attendance)}</span><span>{n(church.sessions)}</span><span>{activityDate(church.lastActivity)}</span></div>)}</div>{!!data.churchActivity.length && <p className="quietChurches">الأقل نشاطًا: {data.churchActivity.slice(-3).reverse().map((church) => church.name).join('، ')}</p>}</article><article className="attentionCard"><header><h2>تحتاج انتباهك</h2><span>{data.repeatedAbsences.length + data.pendingInvitations.length + data.inactiveProfiles.length + summary.unresolvedFollowUps}</span></header><div><b>{data.repeatedAbsences.length}</b><span>مخدومون بغياب متكرر</span><Link href="/admin/data/follow_ups">متابعة ←</Link></div><div><b>{data.pendingInvitations.length}</b><span>دعوات لم تُقبل</span><Link href="/admin/data/invitations">مراجعة ←</Link></div><div><b>{data.inactiveProfiles.length}</b><span>حسابات غير نشطة</span><Link href="/admin/data/profiles">مراجعة ←</Link></div></article></section>

    <section className="dashboardGrid"><article className="tableCard wide"><header><div><h2>أداء الاجتماعات</h2><p>المنضمون الجدد والحضور والغياب والنمو خلال الفترة.</p></div><Link href="/admin/data/meetings">كل الاجتماعات</Link></header><div className="simpleTable performanceTable"><div className="tableHead"><span>الاجتماع</span><span>جدد</span><span>حضور / غياب</span><span>النمو</span></div>{data.meetingPerformance.slice(0, 8).map((meeting) => <div key={meeting.id}><strong>{meeting.name}<small>{meeting.church}</small></strong><span>{n(meeting.newMembers)}</span><span>{n(meeting.present)} / {n(meeting.absent)}</span><span className={meeting.change >= 0 ? 'statusActive' : 'statusQuiet'}>{meeting.change >= 0 ? '+' : ''}{meeting.change}%</span></div>)}</div></article><article className="distributionCard"><h2>الدعوات</h2><p>خلال الفترة المختارة</p><div><span>مرسلة</span><b>{n(summary.invitationStats.sent)}</b></div><div><span>مقبولة</span><b>{n(summary.invitationStats.accepted)}</b></div><div><span>معلّقة</span><b>{n(summary.invitationStats.pending)}</b></div><div><span>مرفوضة</span><b>{n(summary.invitationStats.declined)}</b></div><h3>أكثر مشكلة متكررة</h3><div><span>{data.supportReady ? category(summary.topCategory) : 'غير متاح'}</span><b>{data.supportReady ? 'الدعم' : '—'}</b></div></article></section>

    <section className="dashboardGrid"><article className="chartCard wide"><header><div><h2>اتجاه الحضور</h2><p>الحضور المسجل يوميًا خلال آخر {Math.min(days, 30)} يومًا.</p></div><b>{n(summary.present)}</b></header><AttendanceBars points={data.attendanceTrend} /></article><article className="distributionCard recentChanges"><h2>آخر التعديلات</h2>{data.recentChanges.length ? data.recentChanges.slice(0, 5).map((change, index) => <div key={`${change.at}-${index}`}><span><b>{change.actor}</b> {actionLabel(change.action)} {change.table}</span><small>{new Date(change.at).toLocaleString('ar-EG')}</small></div>) : <div className="emptyMetric">سيظهر السجل بعد تطبيق Migration الإدارة.</div>}</article></section>

    <section className="servantsCard"><header><div><h2>الخدام والصلاحيات</h2><p>كل خادم وتكليفاته في الاجتماعات أو الفصول. استخدم فلتر الكنيسة في الأعلى للتركيز على كنيسة واحدة.</p></div><Link href="/admin/data/class_assignments">إدارة التكليفات</Link></header><form className="servantsSearch"><input name="servantsQ" defaultValue={search.servantsQ ?? ''} placeholder="ابحث باسم الخادم أو الكنيسة…" /><input type="hidden" name="days" value={days} />{search.church && <input type="hidden" name="church" value={search.church} />}<button type="submit">بحث</button></form>{matchingServants.length ? <><div className="servantsList">{visibleServants.map((servant) => <article key={servant.id}><div className="servantHeading"><strong>{servant.name}</strong><span>{servant.church}</span><em>{servant.role}</em></div>{servant.assignments.length ? <ul>{servant.assignments.map((assignment) => <li key={`${servant.id}-${assignment.target}`}><b>{assignment.target}</b><span className={assignment.attendance ? 'permissionYes' : 'permissionNo'}>تسجيل حضور: {assignment.attendance ? 'مسموح' : 'غير مسموح'}</span><span className={assignment.reports ? 'permissionYes' : 'permissionNo'}>تقارير: {assignment.reports ? 'مسموح' : 'غير مسموح'}</span></li>)}</ul> : <p className="noAssignment">لا توجد تكليفات محددة لهذا الخادم.</p>}</article>)}</div><div className="servantsPagination"><span>صفحة {servantPage} من {servantPages}</span>{servantPage > 1 && <Link href={servantsLink(servantPage - 1)}>السابق</Link>}{servantPage < servantPages && <Link href={servantsLink(servantPage + 1)}>التالي</Link>}</div></> : <div className="emptyMetric">لا توجد حسابات خدام مطابقة للفلتر الحالي.</div>}</section>

    <section className="dashboardGrid"><article className="tableCard wide"><header><div><h2>غياب متكرر</h2><p>مخدومون لديهم غياب مرتين أو أكثر خلال الفترة.</p></div><Link href="/admin/data/attendance_records">السجلات</Link></header><div className="nameChips">{data.repeatedAbsences.length ? data.repeatedAbsences.map((entry) => <span key={entry.name}><b>{entry.name}</b> {entry.count} مرات</span>) : <em>لا توجد حالات غياب متكرر في الفترة المختارة.</em>}</div></article><article className="distributionCard"><h2>الحسابات غير النشطة</h2>{data.inactiveProfiles.length ? data.inactiveProfiles.map((profile) => <div key={`${profile.name}-${profile.church}`}><span>{profile.name}</span><b>{profile.church}</b></div>) : <div className="emptyMetric">لا توجد حسابات غير نشطة.</div>}</article></section>
  </main>;
}
